language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
  - "nightly"

services:
  - mysql
  - postgresql
  - mongodb
addons:
  postgresql: "9.4"

env:
  matrix:
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=master

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}
  - pip install setuptools -U
  - pip install virtualenv tox==2.9.1
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- pip install coveralls 
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: TOX_ENV=lint
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.4"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.5"
      env: ENV=functional
      install:
        - pip install tox
        - export PYTHON='coverage run -a'
      before_install: 
        - mysql -e 'CREATE DATABASE test;'
        - psql -c 'CREATE DATABASE test;' -U postgres
      script:
        - DATABASE_URL=sqlite:////tmp/db.sqlite tox -e functional
        - DATABASE_URL=mysql://travis:@localhost/test tox -e functional
        - DATABASE_URL=postgres://postgres:@localhost/test tox -e functional
        - CONNECTOR=dbbackup.db.postgresql.PgDumpBinaryConnector DATABASE_URL=postgres://postgres:@localhost/test tox -e functional
    - python: "3.4"
      env: TOX_ENV=upgrade
      install:
        - pip install tox
        - export PYTHON='coverage run -a'
      before_install: 
        - mysql -e 'CREATE DATABASE test;'
        - psql -c 'CREATE DATABASE test;' -U postgres
      script:
        - DATABASE_URL=sqlite:////tmp/db.sqlite tox -e upgrade
        - DATABASE_URL=mysql://travis:@localhost/test tox -e upgrade
        - DATABASE_URL=postgres://postgres:@localhost/test tox -e upgrade
  exclude:
    - python: "3.5"
      env: DJANGO=1.6
    - python: "nightly"
      env: DJANGO=1.6
    - python: "3.6"
      env: DJANGO=1.6
    - python: "3.5"
      env: DJANGO=1.7
    - python: "3.6"
      env: DJANGO=1.7
    - python: "nightly"
      env: DJANGO=1.7
    - python: "pypy3"
      env: DJANGO=1.9
    - python: "pypy3"
      env: DJANGO=1.10
    - python: "pypy3"
      env: DJANGO=1.11
    - python: "2.7"
      env: DJANGO=master
    - python: "pypy"
      env: DJANGO=master
    - python: "pypy3"
      env: DJANGO=master
    - python: "nightly"
      env: DJANGO=master
  allow_failures:
    - python: "pypy3"
    - python: "nightly"
    - python: "3.7"
    - env: DJANGO=master
